name: Check Streaming URL Availability

on:
  schedule:
    - cron: '*/1 * * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Enables manual triggering

jobs:
  check-availability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Check URL Availability
        run: |
          api_key=$PROXYCRAWL_API_KEY
          urls=(
            "https://ertflix.s.llnwi.net/ertlive/ert1/clrdef24613/index.mpd"
            "https://streamcdnb4-c98db5952cb54b358365984178fb898a.msvdn.net/live/S86713049/gonOwuUacAxM/playlist.m3u8"
            # Add more URLs as needed
          )
          countries=("US" "UK" "JP" "DE" "FR" "GR" "ES" "IT" "AU")  # List of countries to check
          
          for url in "${urls[@]}"; do
            for country in "${countries[@]}"; do
              response=$(curl -s "https://api.proxycrawl.com/?token=$api_key&country_code=$country&url=$url")
              availability=$(echo "$response" | jq -r '.status')
              
              if [ "$availability" = "success" ]; then
                echo "URL $url is available in $country"
              else
                echo "Error: Failed to fetch availability for $url in $country"
              fi
            done
          done

      - name: Commit changes
        run: |
          git config --global user.email "7keyzbeatz@gmail.com"
          git config --global user.name "7keyzbeatz"
          git add channels.json
          git commit -m "Update channel availability"
          git push


name: Update Channel Availability

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Enables manual triggering

jobs:
  update-availability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install jq (to parse JSON)
        run: sudo apt-get install jq

      - name: Update Availability
        run: |
          api_key=$PROXYCRAWL_API_KEY
          countries=("US" "UK" "JP" "DE" "FR")  # List of countries to check
          temp_file=$(mktemp)

          # Read and parse channels.json
          cp channels.json channels.json.backup  # Backup original file
          jq '.TV[] | select(.Video != null) | .Video' channels.json | while read -r video_url; do
            echo "Checking availability for: $video_url"
            available_countries=()

            for country in "${countries[@]}"; do
              response=$(curl -s "https://api.proxycrawl.com/?token=$api_key&country_code=$country&url=$video_url")
              if [[ ! $response =~ "status" ]]; then
                echo "Error: Failed to fetch availability for $video_url in $country - https://api.proxycrawl.com/?token=$api_key&country_code=$country&url=$video_url"
              else
                availability=$(echo "$response" | jq -r '.status')
                if [[ $availability == "200" ]]; then
                  available_countries+=("$country")
                fi
              fi
            done

            # Update channels.json with availability
            jq --argjson avc "$(echo ${available_countries[@]} | jq -R 'split("\n")[:-1] | map({(.):true}) | add')" \
              '.TV |= map(if .Video == $v then .availability = $avc else . end)' --arg v "$video_url" channels.json > "$temp_file" && \
              mv "$temp_file" channels.json
          done

      - name: Commit and push changes
        run: |
          git config --global user.email "7keyzbeatz@gmail.com"
          git config --global user.name "7keyzbeatz"
          git add channels.json
          git commit -m "Update channel availability"
          git push
