name: Check Streaming URL Availability

on:
  schedule:
    - cron: '*/1 * * * *'  # Run daily at midnight UTC

jobs:
  check-availability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Check URL Availability
        run: |
          # Example using ProxyCrawl API
          api_key=$PROXYCRAWL_API_KEY
          urls=(
            "https://ertflix.s.llnwi.net/ertlive/ert1/clrdef24613/index.mpd"
            "https://streamcdnb4-c98db5952cb54b358365984178fb898a.msvdn.net/live/S86713049/gonOwuUacAxM/playlist.m3u8"
            # Add more URLs as needed
          )
          countries=("US" "UK" "JP" "DE" "FR" "GR")  # List of countries to check
          
          for url in "${urls[@]}"; do
            for country in "${countries[@]}"; do
              response=$(curl -s "https://api.proxycrawl.com/?token=$api_key&country_code=$country&url=$url")
              availability=$(echo "$response" | jq -r '.status')
              
              # Update JSON file with availability status
              jq --arg url "$url" --arg country "$country" --arg availability "$availability" \
                '.[] | select(.url == $url) | .availability[$country] = $availability' channels.json > channels.json.tmp && mv channels.json.tmp channels.json
            done
          done

      - name: Commit changes
        run: |
          git config --global user.email "7keyzbeatz@gmail.com"
          git config --global user.name "7keyzbeatz"
          git add channels.json
          git commit -m "Update channel availability"
          git push
