name: Download and Upload Videos

on:
  workflow_dispatch:

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Download "The Last Rifleman (2023)"
      run: curl -k -L -o "The Last Rifleman (2023).mp4" "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"

    - name: Install lftp
      run: sudo apt-get install -y lftp

    - name: List Downloaded Files
      run: ls -l

    - name: Upload Videos to FTP Server
      env:
        FTP_HOST: 'ftp1.voe-network.net'  # Replace with your actual FTP host
        FTP_USER: '7keyzbeatz'            # Replace with your actual FTP username
        FTP_PASS: '3mnyf7mrexvzdh'       # Replace with your actual FTP password
      run: |
        lftp -d -e "
        open -u $FTP_USER,$FTP_PASS $FTP_HOST;
        put 'The Last Rifleman (2023).mp4';
        bye
        " -u $FTP_USER,$FTP_PASS $FTP_HOST

    - name: Clean up
      run: rm "The Last Rifleman (2023).mp4"
