name: Scrape Movie Data

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Base URL for scraping'
        required: true
        default: 'https://gamatotv.info/el/comedy/'
      start_page:
        description: 'Start page number'
        required: true
        default: '1'  # Changed from number to string
        type: string  # Changed from number to string
      end_page:
        description: 'End page number'
        required: true
        default: '10'  # Changed from number to string
        type: string  # Changed from number to string
      include_keywords:
        description: 'Comma-separated list of keywords or phrases to include'
        required: false
        default: ''
        type: string  # Ensure this is treated as string
      exclude_keywords:
        description: 'Comma-separated list of keywords or phrases to exclude'
        required: false
        default: 'Κινούμενα Σχέδια, Μεταγλωτισμένα'
        type: string  # Ensure this is treated as string

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests

    - name: Run Scrape Script
      run: |
        python scripts/grab_gamatotv_movies.py \
          --base_url "${{ github.event.inputs.base_url }}" \
          --start_page "${{ github.event.inputs.start_page }}" \
          --end_page "${{ github.event.inputs.end_page }}" \
          --include_keywords "${{ github.event.inputs.include_keywords }}" \
          --exclude_keywords "${{ github.event.inputs.exclude_keywords }}"

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: movie-data
        path: movies.json
