name: Fetch AdMob Stats

on:
  workflow_dispatch:
    inputs:
      client_id:
        description: 'OAuth 2.0 Client ID'
        required: true
        type: string
      client_secret:
        description: 'OAuth 2.0 Client Secret'
        required: true
        type: string
      authorization_code:
        description: 'OAuth 2.0 Authorization Code'
        required: true
        type: string

jobs:
  fetch-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run script to fetch AdMob stats
        env:
          CLIENT_ID: ${{ github.event.inputs.client_id }}
          CLIENT_SECRET: ${{ github.event.inputs.client_secret }}
          AUTHORIZATION_CODE: ${{ github.event.inputs.authorization_code }}
        run: |
          python fetch_admob_stats.py
