name: Upload File to Archive.org

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Download Remote File
      run: |
        curl -L -o video.mp4 "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
    
    - name: Upload to Archive.org
      env:
        ACCESS_KEY: ${{ secrets.ARCHIVE_ORG_ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.ARCHIVE_ORG_SECRET_KEY }}
      run: |
        curl --location --header 'x-amz-auto-make-bucket:1' \
             --header 'x-archive-meta01-collection:opensource' \
             --header 'x-archive-meta-mediatype:video' \
             --header 'x-archive-meta-sponsor:Andrew W. Mellon Foundation' \
             --header 'x-archive-meta-language:eng' \
             --header "authorization: LOW $ACCESS_KEY:$SECRET_KEY" \
             --upload-file 25xiliades.mp4 \
             http://s3.us.archive.org/your-bucket-name/25xiliades.mp4
