name: Process Movies

on:
  workflow_dispatch:
    inputs:
      max-movies:
        description: 'Maximum number of movies to upload to voe.sx'
        required: true
        default: "25"  # Default value as a string
        type: string  # Type set to string

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the version of Python to use

    - name: Install Dependencies
      run: |
        pip install requests

    - name: Run Movie Upload Script
      env:
        MAX_MOVIES: ${{ github.event.inputs.max-movies }}  # Pass the max-movies input to the script
      run: |
        python process_movies.py $MAX_MOVIES

    - name: Upload updated movies JSON
      uses: actions/upload-artifact@v3
      with:
        name: updated-movies
        path: updated_movies.json
